custom client of tm-load-test
onomyprotocol/tm-load-test pull request #2
Opened 2021-10-29 09:00 UTC by puneetsingh166

Added custom client in "customClient" directory.
Changed module name from "github.com/interchainio/tm-load-test" to "github.com/onomyprotocol/tm-load-test"

2021-10-29 15:31 UTC, dzmitryhil requested changes

2021-10-29 15:31 UTC, dzmitryhil commented on customClient/client.go
> +package main
the code is not a go formatted. Format the code please and push changes. Also I enabled the linters on github workflow, so once you push the shares check the actions result.

2021-10-29 15:31 UTC, dzmitryhil commented on Makefile
> +	go build -o deploy/cosmos-load-test ./customClient/
rename plz customClient -> onomy-load-test and move to cmd folder (cmd/onomy-load-test)

2021-10-29 15:31 UTC, dzmitryhil commented on customClient/tx.go
> +	  fmt.Println("error")
What can be the reason for that error? And why you don't stop the execution if you get the error? The comments is the same for the cases where you check error and then just print it

2021-10-29 15:31 UTC, dzmitryhil commented on customClient/tx.go
> +	  fmt.Println("error")
It is better to start returning the error and forward it in 

```
func (c *MyABCIAppClient) GenerateTx() ([]byte, error) {
	return GenTx() <-- this way
}
```

2021-10-29 15:31 UTC, dzmitryhil commented on customClient/tx.go
> +  txBuilder.SetFeeAmount(sdk.NewCoins(sdk.NewInt64Coin("footoken", 5)))
please make constants for all string variables you use

2021-10-30 07:14 UTC, dzmitryhil requested changes

2021-10-30 07:14 UTC, dzmitryhil commented on cmd/onomy-load-test/README.md
> +# tm-load-test custom client for cosmos chain.
!! @puneetsingh166  Sorry for the late comment, but better move this "customClient" content to onomy tm-load-test, and add this repo as a dependency in gomod. as a result you will not have to copy constants on onomy and will be possible to update the test in onomy repo.  The comments abow still actual anyway !!!

2021-11-01 07:48 UTC, puneetsingh166 reviewed
1. We have removed custom client from here and will move that in onomy repo.
2. This PR is coming with single change that is module name .using github.com/onomyprotocol/tm-load-test.

2021-11-01 09:31 UTC, dzmitryhil approved these changes

2021-11-01 09:34 UTC, merged